// <auto-generated />
using System;
using Lexicon_Miniproject_SQLAssetTracking;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lexicon_Miniproject_SQLAssetTracking.Migrations
{
    [DbContext(typeof(AssetTrackingDBContext))]
    [Migration("20260519135819_AddedDiscriminator")]
    partial class AddedDiscriminator
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lexicon_Miniproject_SQLAssetTracking.DBDevice", b =>
                {
                    b.Property<int>("DBDevice_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DBDevice_Id"));

                    b.Property<string>("DeviceBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DBDevice_Id");

                    b.ToTable("DBDevices");

                    b.HasDiscriminator<string>("DeviceType").HasValue("Base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Lexicon_Miniproject_SQLAssetTracking.DBComputerDevice", b =>
                {
                    b.HasBaseType("Lexicon_Miniproject_SQLAssetTracking.DBDevice");

                    b.HasDiscriminator().HasValue("Computer");
                });

            modelBuilder.Entity("Lexicon_Miniproject_SQLAssetTracking.DBSmartphoneDevice", b =>
                {
                    b.HasBaseType("Lexicon_Miniproject_SQLAssetTracking.DBDevice");

                    b.HasDiscriminator().HasValue("Smartphone");
                });

            modelBuilder.Entity("Lexicon_Miniproject_SQLAssetTracking.DBDevice", b =>
                {
                    b.OwnsOne("Lexicon_Miniproject_SQLAssetTracking.DBPrice", "PurchasePrice", b1 =>
                        {
                            b1.Property<int>("DBDevice_Id")
                                .HasColumnType("int");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("DBDevice_Id");

                            b1.ToTable("DBDevices");

                            b1.WithOwner()
                                .HasForeignKey("DBDevice_Id");
                        });

                    b.Navigation("PurchasePrice")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
